# Generated by Django 3.1.1 on 2021-12-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.IntegerField(max_length=100)),
                ('year', models.IntegerField(max_length=100)),
                ('dacoity', models.IntegerField(max_length=100)),
                ('robbery', models.IntegerField(max_length=100)),
                ('murder', models.IntegerField(max_length=100)),
                ('speedy_trial', models.IntegerField(max_length=100)),
                ('riot', models.IntegerField(max_length=100)),
                ('wcperession', models.IntegerField(max_length=100)),
                ('kidnapping', models.IntegerField(max_length=100)),
                ('policeassult', models.IntegerField(max_length=100)),
                ('burglary', models.IntegerField(max_length=100)),
                ('theft', models.IntegerField(max_length=100)),
                ('othercases', models.IntegerField(max_length=100)),
                ('armsact', models.IntegerField(max_length=100)),
                ('explosive', models.IntegerField(max_length=100)),
                ('nacrotics', models.IntegerField(max_length=100)),
                ('smuggling', models.IntegerField(max_length=100)),
            ],
        ),
    ]
