# Generated by Django 3.1.1 on 2021-12-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='wcperession',
            new_name='wcrepresion',
        ),
    ]
